hl.bind("CTRL+SUPER+ALT+Slash", hl.dsp.exec_cmd("xdg-open ~/.config/hypr/custom/keybinds.lua"), {description = "Edit user keybinds"} )

--##! Apps
--hl.bind("SUPER + Return", hl.dsp.exec_cmd(terminal), { description = "App: Terminal" })
--hl.bind("SUPER + T", hl.dsp.exec_cmd(terminal))
--hl.bind("CTRL + ALT + T", hl.dsp.exec_cmd(terminal))
--hl.bind("SUPER + E", hl.dsp.exec_cmd(fileManager), { description = "App: File manager" })
--hl.bind("SUPER + W", hl.dsp.exec_cmd(browser), { description = "App: Browser" })
hl.bind("SUPER + B", hl.dsp.exec_cmd(brave), { description = "App: Brave Browser" })
--hl.bind("SUPER + C", hl.dsp.exec_cmd(codeEditor), { description = "App: Code editor" })
--hl.bind("CTRL + SUPER + SHIFT + ALT + W", hl.dsp.exec_cmd(officeSoftware), { description = "App: Office software" })
--hl.bind("SUPER + X", hl.dsp.exec_cmd(textEditor), { description = "App: Text editor" })
--hl.bind("CTRL + SUPER + V", hl.dsp.exec_cmd(volumeMixer), { description = "App: Volume mixer" })
--hl.bind("SUPER + I", hl.dsp.exec_cmd(settingsApp), { description = "App: Settings app" })
--hl.bind("CTRL + SHIFT + Escape", hl.dsp.exec_cmd(taskManager), { description = "App: Task manager" })
hl.bind("SUPER + ALT + B", hl.dsp.exec_cmd(taskManager), { description = "App: Task manager" })
hl.bind("SUPER + O", hl.dsp.exec_cmd(obsidian), { description = "App: Notes on MarkDown files" })
