-- ######## Window rules ########

-- Floating
hl.window_rule({match = {class = "^(steam)$" },                                 center = true})
hl.window_rule({match = {class = "^(steam)$" },                                 float = true})
hl.window_rule({match = {class = "^(org.kde.ark)$" },                           center = true})
hl.window_rule({match = {class = "^(org.kde.ark)$" },                           float = true})
hl.window_rule({match = {class = "^(transmission-qt)$" },                       center = true})
hl.window_rule({match = {class = "^(transmission-qt)$" },                       float = true})
hl.window_rule({match = {class = "^(org.gnome.seahorse.Application)$" },        center = true})
hl.window_rule({match = {class = "^(org.gnome.seahorse.Application)$" },        float = true})
hl.window_rule({match = {class = "^(blueman-manager)$" },                       center = true})
hl.window_rule({match = {class = "^(blueman-manager)$" },                       float = true})
hl.window_rule({match = {class = "^(nwg-displays)$" },                          center = true})
hl.window_rule({match = {class = "^(nwg-displays)$" },                          float = true})
hl.window_rule({match = {class = "^(io.missioncenter.MissionCenter)$" },        center = true})
hl.window_rule({match = {class = "^(io.missioncenter.MissionCenter)$" },        float = true})
hl.window_rule({match = {class = "^(virt-manager)$" },                          center = true})
hl.window_rule({match = {class = "^(virt-manager)$" },                          float = true})
hl.window_rule({match = {class = "^(org.kde.plasma.emojier)$" },                center = true})
hl.window_rule({match = {class = "^(org.kde.plasma.emojier)$" },                float = true})
hl.window_rule({match = {class = "^(com.interversehq.qView)$" },                center = true})
hl.window_rule({match = {class = "^(com.interversehq.qView)$" },                float = true})
hl.window_rule({match = {class = "^(PacketTracer)$" },                          center = true})
hl.window_rule({match = {class = "^(PacketTracer)$" },                          float = true})
hl.window_rule({match = {class = "^(brave-browser)$" },                         center = true})
hl.window_rule({match = {class = "^(brave-browser)$" },                         float = true})
